### ISSUE TITLE
Ensuring full compatibility between Double loop notebooks and upstream IDAES

### ISSUE THREAD

**Issue by lbianchi-lbl** [gmlc-dispatches/dispatches#154]
### Notebooks

- [x] `DoubleLoopOptimization.ipynb`
  - [x] Class `ThermalGeneratorModelData` seems to be missing from current IDAES
    - [x] Need a PR in IDAES or DISPATCHES adding this class IDAES/idaes-pse#986
  - [x] Something in the notebook itself might need adaptation to IDAES v2 API - if so, it should be easy to fix
- [x] NE and FE double loop notebooks need to be updated to use IDAES/idaes-pse#996
- [ ] ~~Cell 10 raises exception on Linux because of capitalization issues in the GMLC-RTS dataset (see https://github.com/gmlc-dispatches/sample-data/issues/1)~~ This is a separate issue and is being tracked in #159
### Python code

- [x] Remove explicit version check

**Comment by dguittet** [comment]
Updated the title to reflect all double loop notebook

Added new items:

1. Merge https://github.com/IDAES/idaes-pse/pull/996. This is another IDAES PR that needs to be merged so that the NE and FE flowsheets can work. 
2. Merge #155. The NE and FE flowsheets have been updated alongside the RE one and should now run without problems...

**Comment by dguittet** [comment]
@lbianchi-lbl How should I modify the checks.yml so that we can run the RE double loop notebook with the new CI env var?

**Comment by lbianchi-lbl** [comment]
> @lbianchi-lbl How should I modify the checks.yml so that we can run the RE double loop notebook with the new CI env var?

@dguittet In the `.github/workflows/notebooks-checks.yml` file, it should be enough to add this at the root level of the YAML tree (i.e. `env` should not be indented), e.g. between the `defaults` and `jobs` top-level keys at line 11:

```yaml
on:
  workflow_dispatch:

defaults:
  run:
    # important to make sure that all commands on Windows are run using Bash
    # -l: login shell, needed when using Conda
    shell: bash -l {0}

env:
  DISPATCHES_TESTING_MODE: "true"

jobs:
  # ... rest of the code
```

**Comment by dguittet** [comment]
@lbianchi-lbl Thanks. And the notebook is already enabled?

**Comment by lbianchi-lbl** [comment]
@dguittet good point. The last several cells of `DoubleLoopOptimization.ipynb` have a `nbval-skip` tag that needs to be removed from each cell in order for that cell to be run.

That can be done:

- Either through the JupyterLab (or "classic notebook") interface
- Or by opening the `.ipynb` as a text/JSON file and that tag from the `tags: [...]` array (leaving the empty array should be fine)

**Comment by lbianchi-lbl** [comment]
Since it's not really connected to the IDAES v2 transition, I've created #159 to track the changes needed to be able to remove the `nbval-skip` tags for the DL notebooks, and closing this as the remaining items have been completed.
