### ISSUE TITLE
Code requiring access to external data

### ISSUE THREAD

**Issue by lbianchi-lbl** [gmlc-dispatches/dispatches#180]
- Some parts of the DISPATCHES codebase require access to off-repository datasets
- This is being accomplished by separate data packages that the DISPATCHES code can access in a standardized way
 
This is a meta-issue to keep track of the progress with:
1. Setting up the appropriate data package
2. Connecting the data package with the DISPATCHES code requiring it

## For March release

- [x] [gmlc-dispatches/dynamic-sweep-data](https://github.com/gmlc-dispatches/dynamic-sweep-data) (needed by: #163)
- [x] [gmlc-dispatches/synthetic-price-data](https://github.com/gmlc-dispatches/synthetic-price-data) (needed by: #177)

## For June release

- [x] [gmlc-dispatches/steady-state-sweep-data](https://github.com/gmlc-dispatches/steady-state-sweep-data) (needed by: #142)

## For code already in the repository

- [x] [gmlc-dispatches/rts-gmlc-data](https://github.com/gmlc-dispatches/rts-gmlc-data) (needed by #183)
