### ISSUE TITLE
July (internal) release goals

### ISSUE THREAD

**Issue by ksbeattie** [gmlc-dispatches/dispatches#45]
This is a list of goals for the July internal release (targeting paper/technical report for simple system: 8/31):

- [x] Models: We need to pivot and start getting documentation in place
  - [x] Case Studies:
    - [x] Nuclear:
      - [x] Hydrogen Turbine: Konor PR #27 
        - [x] model
        - [x] docs (PR #50)
        - [x] tests
      - [x] Hydrogen Tank: Naresh S PR #34, #51 & #61
      - [x] Electrolyzer: Darice PR #11 (merged)
    - [x] Renewables: Issue #14
      - [x] Electricity Splitter: Darice PR #39 (merged)
      - [x] Lithium Ion Battery: Darice PR #37 (merged)
      - [x] Wind Turbine: Darice PR #36
    - [x] Fossil:
      - [x] Existing power plant: Andres PR #40
      - [x] Ultra super-Critical: Naresh PR #38 and PR #67
      - [x] Thermal Oil: Konor PRs #4 & #9 (both merged)
      - [x] Molten Salt: Naresh PR #57
      - [x] CCS: Naresh (Will be done in PR #69 in Jan (internal release)) 
      - [x] Concrete Thermal Storage: Jaffer PR #30
        - [x] docs: Dan (PR #58)
- [x] Grid/surrogates: (applied to simple system) (@jghouse88)  PR #62
- [x] Work flow: documented (@jalving, @jghouse88, @adowling2) PR #62

**Comment by ksbeattie** [comment]
@jghouse88 who will be working on the last 2 checkboxes here?

**Comment by adowling2** [comment]
@ksbeattie We are a little delayed on the last two checkboxes. I'll be working on them with @jalving and @jghouse88.

**Comment by ksbeattie** [comment]
@Andresj89: Did PR #40 complete the above checkbox?
@nareshsusarla: Are the Fossil docs above coming along?

**Comment by ksbeattie** [comment]
@adowling2, any update on the last two checks here?

**Comment by adowling2** [comment]
@ksbeattie Effort is in progress. I'd prefer to not write documentation until we have converged on the workflow. What do you think about creating placeholder pages?

**Comment by ksbeattie** [comment]
> @ksbeattie Effort is in progress. I'd prefer to not write documentation until we have converged on the workflow. What do you think about creating placeholder pages?

@adowling2 placeholder pages would be fine.  Mostly just trying to get the box checked, and exercise all the steps for creating a first, very internal, release done.
