### ISSUE TITLE
April/May 2022 Release Goals (internal)

### ISSUE THREAD

**Issue by adowling2** [gmlc-dispatches/dispatches#65]
Overall goal: code for reproducing (subset of) results for milestone Task 2.2 Y2Q2 (Dec 2021) superstructure optimization milestone.  Each of the following should have (for the March release)

- Working model of the case study
- Basic tests in place
- Basic documentation started

- [x] Nuclear case study: (Konor & Radhakrishna) #84 
- [x] Renewables case study: (Darice) #60 & #106
- [x] Fossil case study: (Jaffer & Naresh) #99, #118 & #119
- [ ] General tools (optional, Jaffer & Radhakrishna) moved to Jan release: #107

**Comment by ksbeattie** [comment]
@adowling2, can you elaborate on the "General tools" checkbox above?

**Comment by adowling2** [comment]
Any shared code we develop across the case studies. For example, we might decide to create 'superstructure_methods.py' that contains shared methods. IMO, this will come together once draft PRs for the case studies appear and we can start thinking about how to generalize.

**Comment by dguittet** [comment]
For the flowsheet tests, we need to import the MultiPeriod Model, which currently lives on Xian's andJordan's forks. My tests for #60 are going to be failing until either the code is merged into idaes or we use a different version of idaes to test against.

**Comment by radhakrishnatg** [comment]
@dguittet Other than the `MultiPeriodModel` class, do you need any other code from Xian and Jordan's branch for #60? During Monday's dev call, we discussed adding a copy of the `MultiPeriodModel` class code to the dispatches repository temporarily until Xian and Jordan's branch is merged. This way we can merge your PR after you finalize the changes and a couple other PRs in the next few weeks.
