### ISSUE TITLE
June 2022 Release Goals (external)

### ISSUE THREAD

**Issue by adowling2** [gmlc-dispatches/dispatches#66]
Overall goal: code for reproducing (subset of) results for milestone Task 3.2 Y2Q3 integrated analysis milestone

**Dependencies:**
- [x] IDAES release with the following PRs merged: @ksbeattie @lbianchi-lbl 
   - [x] IDAES double loop plug-in: @xiangao1 https://github.com/IDAES/idaes-pse/pull/638
- [x] Prescient release (or identify suitable existing release) @bknueven
   - [x] #89  
- [ ] RAVEN??? Moved to Jan release https://github.com/gmlc-dispatches/dispatches/issues/76 

**General tools: all moved to Jan**
- [ ] (Steady-state) market surrogate training @Xinhe-Chen #107
   - [ ] All code documented, reviewed, and merged
   - [ ] Basic documentation complete
   - [ ] Jupyter notebook demonstrating workflow
- [ ] Prescient results data analysis @xiangao1 (no longer part of June release)
   - [ ] All code documented, reviewed, and merged
   - [ ] Basic documentation complete
   - [ ] Jupyter notebook demonstrating capabilities
- [ ] #90 

**Nuclear case study:** @radhakrishnatg @klfrick2 
- [x] All models documented, reviewed and merged
- [x] Basic documentation complete
- [x] Jupyter notebook demonstrating:
   - [x] Design and operations co-optimization #84 
   - [x] Simulation with double-loop #103 

**Renewables case study:** @dguittet 
- [x] All models documented, reviewed and merged #106 #60 
- [x] Basic documentation complete #106 
- [x] Jupyter notebook demonstrating:  
   - [x] Design and operations co-optimization #106 
   - [x] Simulation with double-loop #95 

**Fossil case study:** @esrawli @nareshsusarla 
- [x] All models documented, reviewed and merged #99 , #118 , #119 
- [x] Basic documentation complete #118 
- [x] Jupyter notebook demonstrating: #119 
   - [x] Design and operations co-optimization #119 
   - [x] Simulation with double-loop #119
