### ISSUE TITLE
Analyze renewables case study with double loop

### ISSUE THREAD

**Issue by adowling2** [gmlc-dispatches/dispatches#80]
Lead: @xiangao1 @dguittet 

Support: @bknueven @isatkaus 

### Summary

**The goal for March 31, 2022**: Successfully link RE case study with double loop via multi-period model interface and simulate for multiple days (up to 1 year). Complete preliminary analysis of the findings. Investigate the impact of optimal participation vs baseline Prescient simulation.

**Important Code**:
- IDAES PR for double loop plug-in: https://github.com/IDAES/idaes-pse/pull/638
- DISPATCHES PR for case study models: 

### Tasks and Working Timeline

**Week 1: 02/15 - 02/21**

 
Goal: Right-hand side of the double loop (bidding/self-scheduling) can simulate a week
Steps:

- [x] Find the necessary renewable time-series data for the IES. May need to ask people from NREL
- [x] Make sure the date of the time-series data matches that of Prescient
- [x] Function to update the model in rolling horizon
- [x] Pass the correct renewable data
- [x] Update the energy storage level
- [x] Function to record the results for the model
- [x] Simulate with Prescient
- [x] Regression unit test: solve the bidding problem once
- [x] Whether it solves
- [x] Check against the known solution

**Week 2: 02/22 - 02/28**
 
Goal: Left-hand side of the double loop (Tracking) can simulate a week
Steps:

- [x] Simulate with Prescient
- [x] Check if the  dispatches are feasible
- [x] Regression unit test: solve the tracking problem once
- [x] Whether it solves
- [x] Check against the known solution

**Week 3: 03/01 - 03/07**
 
Goal: The full double loop (bidding + Tracking) can simulate a week
 
Steps:

- [x] Initialize the models (bidder and tracker) with the correct length of the horizon, i.e., 4 hours for the Tracker, 24+ for Bidder
- [x] Make sure the models (bidder and tracker) have the same design variables values, e.g., capacity
- [x] Simulate with Prescient

 
**Week 4: 03/08 - 03/14**
 
Goal: Analyze the results from the one-week simulation
Steps:

- [x] Make sure Tracker and Bidder record the customized results
- [x] Run the simulation without the double loop for comparison
- [x] Make plots/tables to compare the results
- [x] Power generated
- [x] dispatches
- [x] Profit

 
**Week 5: 03/15 - 03/21**
 
If things don’t go as planned, I will try to fix them this week.
 
**Week 6: 03/22 - 03/31**
 
Goal: Start working on 1-year simulation
